apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    label2: value2
  #tolerations:
  #- key: "taint1"
  #  operator: "Equal"
  #  value: "taint_value_1"
  #  effect: "NoSchedule"