#!/usr/bin/env bash

echo -n "Enter a prefix to be used in the image filenames (e.g. arj123): "
read prefix

for i in 1 2 3 4 5 6
do
  curl https://github.com/IBM/SalesEnablement-COS-L3/blob/main/docs/includes/checkImages/check${i}.jpg
  mv check${i}.jpg ${prefix}-check${i}.jpg
done

exit
